// Order Action
export const RETRIEVE_ORDERS = "RETRIEVE_ORDERS";

export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAILURE = 'PLACE_ORDER_FAILURE';


// Customer Action
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const RETRIEVE_CUSTOMERS = 'RETRIEVE_CUSTOMERS';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const FIND_CUSTOMERS_BY_NAME = 'FIND_CUSTOMERS_BY_NAME';

// User Action
export const REGISTER_USER = 'REGISTER_USER';
export const FIND_USER_BY_ID = 'FIND_USER_BY_ID';
export const UPDATE_USER = 'UPDATE_USER';