// Order Action
export const RETRIEVE_ORDERS = "RETRIEVE_ORDERS";
export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAILURE = 'PLACE_ORDER_FAILURE';
export const UPDATE_ORDER = "UPDATE_ORDER";

// Category Action 
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const RETRIEVE_CATEGORYS = 'RETRIEVE_CATEGORYS';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_ALL_CATEGORYS = 'DELETE_ALL_CATEGORYS';
export const FIND_CATEGORYS_BY_NAME = 'FIND_CATEGORYS_BY_NAME';

// Product Action
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const RETRIEVE_PRODUCTS = "RETRIEVE_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_ALL_PRODUCTS = "DELETE_ALL_PRODUCTS";

// OrderStatus Action
export const RETRIEVE_ORDER_STATUS = "RETRIEVE_ORDER_STATUS";
export const CREATE_ORDER_STATUS_REQUEST = "CREATE_ORDER_STATUS_REQUEST";
export const CREATE_ORDER_STATUS_SUCCESS = "CREATE_ORDER_STATUS_SUCCESS";
export const CREATE_ORDER_STATUS_FAILURE = "CREATE_ORDER_STATUS_FAILURE";
export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAILURE = "UPDATE_ORDER_STATUS_FAILURE";
export const DELETE_ORDER_STATUS = "DELETE_ORDER_STATUS";

export const RETRIEVE_SINGLE_ORDER_STATUS = "RETRIEVE_SINGLE_ORDER_STATUS";
export const RETRIEVE_ORDER_STATUS_FAILURE = "RETRIEVE_ORDER_STATUS_FAILURE";


// Order Items Action Types
export const RETRIEVE_ORDER_ITEMS = "RETRIEVE_ORDER_ITEMS";

export const ADD_ORDER_ITEM_REQUEST = "ADD_ORDER_ITEM_REQUEST";
export const ADD_ORDER_ITEM_SUCCESS = "ADD_ORDER_ITEM_SUCCESS";
export const ADD_ORDER_ITEM_FAILURE = "ADD_ORDER_ITEM_FAILURE";

export const UPDATE_ORDER_ITEM_REQUEST = "UPDATE_ORDER_ITEM_REQUEST";
export const UPDATE_ORDER_ITEM_SUCCESS = "UPDATE_ORDER_ITEM_SUCCESS";
export const UPDATE_ORDER_ITEM_FAILURE = "UPDATE_ORDER_ITEM_FAILURE";

export const DELETE_ORDER_ITEM_REQUEST = "DELETE_ORDER_ITEM_REQUEST";
export const DELETE_ORDER_ITEM_SUCCESS = "DELETE_ORDER_ITEM_SUCCESS";
export const DELETE_ORDER_ITEM_FAILURE = "DELETE_ORDER_ITEM_FAILURE";
